import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

file = pd.read_csv('output.csv')

plt.figure()
plt.subplot(2, 1, 1)
plt.plot(file['xd'].values, file['yd'].values, label='desired', color='black', linestyle='dashed')
plt.plot(file['x'].values, file['y'].values, label='actual', color='red')
plt.title('trajectory')
plt.xlabel('x [m]')
plt.ylabel('y [m]')
plt.grid()
plt.legend()
plt.subplot(2, 1, 2)
plt.plot(file['t'].values, file['zd'].values, label='desired', color='black', linestyle='dashed')
plt.plot(file['t'].values, file['z'].values, label='actual')
plt.xlabel('t [s]')
plt.ylabel('z [m]')
plt.grid()
plt.legend()

plt.figure()
plt.subplot(2, 1, 1)
plt.plot(file['t'].values, np.degrees(file['phid'].values), label='desired phi', color='black', linestyle='dashed')
plt.plot(file['t'].values, np.degrees(file['thetad'].values), label='desired theta', color='black', linestyle='dashed')
plt.plot(file['t'].values, np.degrees(file['phi'].values), label='actual phi', color='red')
plt.plot(file['t'].values, np.degrees(file['theta'].values), label='actual theta', color='green')
plt.title('attitude')
plt.xlabel('t [s]')
plt.ylabel('angle [deg]')
plt.legend()
plt.grid()
plt.subplot(2, 1, 2)
plt.plot(file['t'].values, np.degrees(file['psid'].values), label='desired psi', color='black', linestyle='dashed')
plt.plot(file['t'].values, np.degrees(file['psi'].values), label='actual psi')
plt.xlabel('t [s]')
plt.ylabel('angle [deg]')
plt.legend()
plt.grid()

plt.figure()
plt.subplot(2, 1, 1)
plt.plot(file['t'].values, np.degrees(file['a1'].values), label='servo 1')
plt.plot(file['t'].values, np.degrees(file['a2'].values), label='servo 2')
plt.plot(file['t'].values, np.degrees(file['a3'].values), label='servo 3')
plt.plot(file['t'].values, np.degrees(file['a4'].values), label='servo 4')
plt.title('control signals')
plt.xlabel('t [s]')
plt.ylabel('thrust vanes [deg]')
plt.ylim((-10, 10))
plt.legend()
plt.grid()
plt.subplot(2, 1, 2)
plt.plot(file['t'].values, file['w'].values, color='black')
plt.xlabel('t [s]')
plt.ylabel('rotor [rad/s]')
plt.grid()

plt.figure()
plt.subplot(2, 1, 1)
plt.plot(file['t'].values, file['x'].values - file['xd'].values, label='x')
plt.plot(file['t'].values, file['y'].values - file['yd'].values, label='y')
plt.plot(file['t'].values, file['z'].values - file['zd'].values, label='z')
plt.title('trajectory errors')
plt.xlabel('t [s]')
plt.ylabel('e [m]')
plt.grid()
plt.legend()
plt.subplot(2, 1, 2)
plt.plot(file['t'].values, np.degrees(file['phi'].values - file['phid'].values), label='phi')
plt.plot(file['t'].values, np.degrees(file['theta'].values - file['thetad'].values), label='theta')
plt.plot(file['t'].values, np.degrees(file['psi'].values - file['psid'].values), label='psi')
plt.xlabel('t [s]')
plt.ylabel('e [deg]')
plt.grid()
plt.legend()

plt.show()
