import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

file = pd.read_csv('output.csv')

plt.figure()
plt.subplot(2, 1, 1)
#plt.plot(file['xd'].values, file['yd'].values, label='desired', color='black', linestyle='dashed')
plt.plot(file['x'].values, file['y'].values, label='xy')
plt.title('trajectory')
plt.xlabel('x [m]')
plt.ylabel('y [m]')
plt.grid()
plt.legend()
plt.subplot(2, 1, 2)
#plt.plot(file['t'].values, file['zd'].values, label='desired', color='black', linestyle='dashed')
plt.plot(file['t'].values, file['z'].values, label='z')
plt.xlabel('t [s]')
plt.ylabel('z [m]')
plt.xlim(0, max(file['t'].values))
plt.grid()
plt.legend()

plt.figure()
plt.subplot(2, 1, 1)
plt.plot(file['t'].values, np.degrees(file['phi'].values), label='$\phi$')
plt.plot(file['t'].values, np.degrees(file['theta'].values), label='$\\theta$')
plt.title('attitude')
plt.xlabel('t [s]')
plt.ylabel('angle [deg]')
plt.yticks([-45, -30, -15, 0, 15, 30, 45])
plt.xlim(0, max(file['t'].values))
plt.legend()
plt.grid()
plt.subplot(2, 1, 2)
plt.plot(file['t'].values, np.degrees(file['psi'].values), label='$\psi$')
plt.xlabel('t [s]')
plt.ylabel('angle [deg]')
plt.yticks([-180, -135, -90, -45, 0, 45, 90, 135, 180])
plt.xlim(0, max(file['t'].values))
plt.legend()
plt.grid()

plt.figure()
plt.subplot(2, 1, 1)
plt.plot(file['t'].values, np.degrees(file['a1'].values), label='servo 1')
plt.plot(file['t'].values, np.degrees(file['a2'].values), label='servo 2')
plt.plot(file['t'].values, np.degrees(file['a3'].values), label='servo 3')
plt.title('control signals')
plt.xlabel('t [s]')
plt.ylabel('thrust vanes [deg]')
plt.xlim(0, max(file['t'].values))
plt.ylim((-15, 15))
plt.legend()
plt.grid()
plt.subplot(2, 1, 2)
plt.plot(file['t'].values, file['dbeta'].values)
plt.xlabel('t [s]')
plt.ylabel('rotor [rad/s]')
plt.xlim(0, max(file['t'].values))
plt.grid()

#def plotdiff(x, y, **kwargs):
#    plt.plot(x, np.gradient(y)/np.gradient(x), **kwargs)
#
#plt.figure()
#plt.subplot(2, 1, 1)
#plotdiff(file['t'].values, np.degrees(file['a1'].values), label='servo 1')
#plotdiff(file['t'].values, np.degrees(file['a2'].values), label='servo 2')
#plotdiff(file['t'].values, np.degrees(file['a3'].values), label='servo 3')
#plotdiff(file['t'].values, np.degrees(file['a4'].values), label='servo 4')
#plt.title('control signals rate of change')
#plt.xlabel('t [s]')
#plt.ylabel('thrust vanes [deg/s]')
#plt.ylim((-40, 40))
#plt.legend()
#plt.grid()
#plt.subplot(2, 1, 2)
#plotdiff(file['t'].values, file['w'].values, color='black')
#plt.xlabel('t [s]')
#plt.ylabel('rotor [rad/s2]')
#plt.grid()

#plt.figure()
#plt.subplot(2, 1, 1)
#plt.plot(file['t'].values, file['x'].values - file['xd'].values, label='x')
#plt.plot(file['t'].values, file['y'].values - file['yd'].values, label='y')
#plt.plot(file['t'].values, file['z'].values - file['zd'].values, label='z')
#plt.title('trajectory errors')
#plt.xlabel('t [s]')
#plt.ylabel('e [m]')
#plt.grid()
#plt.legend()
#plt.subplot(2, 1, 2)
#plt.plot(file['t'].values, np.degrees(file['phi'].values - file['phid'].values), label='phi')
#plt.plot(file['t'].values, np.degrees(file['theta'].values - file['thetad'].values), label='theta')
#plt.plot(file['t'].values, np.degrees(file['psi'].values - file['psid'].values), label='psi')
#plt.xlabel('t [s]')
#plt.ylabel('e [deg]')
#plt.grid()
#plt.legend()

plt.show()
